name: Test Backend on Pull Request

on:
  pull_request:
    branches: [main, staging]
    paths:
      - "services/backend/**"
      - ".github/workflows/test-backend-workflow.yml"

jobs:
  linter:
    name: Apply Ruff Linter to Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          echo "Ruff Installed"
      - name: Apply Ruff Linter
        run: |
          ruff check --fix --exit-non-zero-on-fix --show-fixes
          echo "Ruff Check and Fix Applied" 
          ruff format .
          echo "File formatting applied"
      - name: Commit formatted changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated code fixes and formatting by ruff"
  test:
    needs: linter
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Dependencies Installed"

      - name: Test with pytest
        run: |
          pytest
          echo "Test Successful"
